### ISSUE TITLE
0.4 Issue with social signin

### ISSUE THREAD

**Issue by IVLMediaInc** [meanjs/generator-meanjs#102]
So if I enter http://localhost:3000/api/auth/facebook it will do the usual sign in process (go to facebook, get auth, redirect etc)....but if I click a link in an anchor <a href="/api/auth/facebook">Sign in with facebook</a> it does absolutely nothing. I am wondering if this is an issue anyone else is encountering. Seems a bit odd. I also tried with the absolute url and same thing, yet as stated if I actually go to the api route by entering it in the address bar, it works correctly.

Thank you.

**Comment by lirantal** [comment]
@IVLMediaInc you opened this issue in generator-meanjs project but in the yeoman generator we don't support 0.4... it's basically based on 0.3.3

Can you clarify?

**Comment by IVLMediaInc** [comment]
It's not an issue with the generator per se, just an issue I've noticed. The stack works fine, but clicking an anchor that links to "/api/auth/facebook" results in no action...while directly going typing /api/auth/facebook does indeed redirect and successfully authenticate via facebook.

I have not noticed these same issues with the 0.3 branch.

I updated passport/passport-facebook etc in order to work with the updated facebook api.

**Comment by lirantal** [comment]
So this is happening with the latest version of 0.4.0 repository?
If you can provide a PR with the fix we'll be happy to merge.

On Sun, Aug 2, 2015 at 8:33 AM, IVLMediaInc <notifications@github.com>
wrote:

> It's not an issue with the generator per se, just an issue I've noticed.
> The stack works fine, but clicking an anchor that links to
> "/api/auth/facebook" results in no action...while directly going typing
> /api/auth/facebook does indeed redirect and successfully authenticate via
> facebook.
>
> I have not noticed these same issues with the 0.3 branch.
>
> I updated passport/passport-facebook etc in order to work with the updated
> facebook api.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/generator-meanjs/issues/102#issuecomment-126990224>
> .
>



-- 
--
Sincerely, Liran Tal

Author
<http://www.amazon.com/Agile-Software-Development-HP-Manager/dp/1484210352/>of
Agile Software Development with HP Agile Manager
Founder and Lead Developer of daloRADIUS <http://www.daloradius.com/>
Blogging at http://www.enginx.com, and tweeting at @liran_tal
<https://twitter.com/liran_tal>

**Comment by IVLMediaInc** [comment]
Sorry, to clarify...it is not with the most recent 0.4 repository. It is using the 0.4-dev generator, and I had just updated the parts I needed. I do realize the 0.4-generator has not been synced with the branch, but it seems rather odd that manually entering the route and hitting enter results in it working, while it does not execute in an anchor tag.

Thought someone else may have experienced this

**Comment by codydaig** [comment]
@IVLMediaInc The 0.4-dev generator is broken. It doesn't have the latest code base, so it's expected to have issues. I'd highly recommend you clone the mean repo and use the 0.4.0 branch (https://github.com/meanjs/mean/tree/0.4.0). That will get you the latest, working code.

**Comment by IVLMediaInc** [comment]
Gotcha. I'll finish writing my application then integrate with a cloned repo. Seems like the most efficient way to go about it since the generators do save a bit of time scaffolding new files.

Take care, thanks. Also, when is the 0.4-dev generator expected to be synced with the 0.4-dev branch?

**Comment by lirantal** [comment]
@IVLMediaInc at the moment no one is set to work on the 0.4 version for the generator. If you'd like to step up for this work, we'd appreciate that

**Comment by IVLMediaInc** [comment]
I'm afraid I'm not quite at the skill level to quickly and efficiently be a contributor to project at this time. My experience with development has been about 3 months now, prior to that my focus was on UI/UX. If I feel my ability gets up to par, I'll definitely see about contributing in what ways I can.

-K.B.

**Comment by lirantal** [comment]
@IVLMediaInc Cool.
