### ISSUE TITLE
Generating Admin module similar to User Module

### ISSUE THREAD

**Issue by bohrasankalp** [meanjs/generator-meanjs#107]
How would I generate admin module similar to user having all authentication and route path required for "Admin" ? Is their any way to do so? I want it to be autogenerated that follows admin routing.

**Comment by codydaig** [comment]
There currently is no generator for the admin section. That's part of 0.4 and the generator is on 0.3. I am working on the 0.4 generator and hope to have that as an option.

**Comment by lirantal** [comment]
Indeed.
We'll update further about the generator for 0.4 when there's something to update.

@bohrasankalp however you are welcome to contact @codydaig on our gitter chat and help with the work for the generator.
