### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by redlive** [meanjs/generator-meanjs#109]
I downloaded MeanJs project from Github and used Yo generator to create new CRUD module by using next command:

yo meanjs:crud-module xxxx

But it looks like the module been created in different location, not the same location where other modules are located... and the module menu wasn't visible at top menu, however I been asked to give a location...

How to create a new module if I'm not using YO MeanJs generator? Please take a look on screenshot.

http://pasteboard.co/oGBAGPF.png

Folder /MODULE created by default from GIT repository, but after running g YO generator creates new folder /APP and new module content was added to that folder.

PS. I'm using v0.3 meanjs and following all steps described in documentation.

**Comment by codydaig** [comment]
@redlive The /modules is part of the 0.4 version of MEAN.js. So it seems like your using the 0.4 version of MEAN.js which does not have a working generator at this time. There's an open PR to get it updated and we're in the final stages of wrapping up the main generator, but still have work to do on the sub generators.
