### ISSUE TITLE
Currently in Progress

### ISSUE THREAD

**Issue by codydaig** [meanjs/generator-meanjs#112]
@ilanbiala You mentioned some changes that you were going to make. Can you elaborate on what those changes are so we don't duplicate efforts accidentally. 

@mleanos You said that you were going to work on the chat sub generator. Is this correct?

@codydaig Per @lirantal I'm going to switch the promise library from Bluebird to q. I'm also going to make a sub generator to do what https://github.com/meanjs/mean/pull/890 does except allow the user specify which module they want to add a server config file too.

**Comment by mleanos** [comment]
@codydaig Yes. I'll create the sub-generator for the Chat module. It's not a high priority, but I think it's definitely needed.

**Comment by lirantal** [comment]
Sounds good.

**Comment by ilanbiala** [comment]
@lirantal @codydaig why switch from Bluebird to Q. The other question is why not just use native promises since Node and io.js have converged and we can finally start pushing our Node dep up?

**Comment by codydaig** [comment]
@ilanbiala There's some functionality that bluebird or q have over the native promise functionality. I use one of them where it allows an array of promisified functions to be ran async, but then doesn't get to the .then() until all have completed.

**Comment by ilanbiala** [comment]
@codydaig you use it in this repo or in general? I'm pretty sure bluebird is still faster than native, but I think it's better to encourage ES6 and use native JS than a library.

**Comment by codydaig** [comment]
@ilanbiala  https://github.com/meanjs/generator-meanjs/blob/master/app/index.js#L146

**Comment by ilanbiala** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by codydaig** [comment]
Then don't we loose support for node 0.10?

**Comment by ilanbiala** [comment]
In the generator, yes, but honestly 0.10 was released quite long ago and we shouldn't hold back our code for the small percentage that don't want to update Node. We'll never be able to make progress if we do that.

**Comment by codydaig** [comment]
Whatever the framework supports, I think we need to support as well over here. I'm not opposed to dropping 0.10, but I know there's a lot of people active in the project that still use 0.10.

**Comment by lirantal** [comment]
@ilanbiala I'm not sure that statement about 0.10 is true.
It is very common for nodejs deployments to rely on nodejs package from their distribution vendor and not everyone build from source the bleeding edge. Latest Ubuntu LTS for example, still has 0.10 in it's repository: http://packages.ubuntu.com/search?keywords=nodejs&searchon=names&suite=all&section=all

Also if you inspect https://nodejs.org/en/download/releases/ then v4.0 is bleeding edge, it was only recently released and TBH I think the majority of users didn't yet move out from 0.10 and 0.12 to io.js's later versions.

But let's get back to the Promises discussion. Which is the latest version of NodeJS which has this support built-in?

**Comment by codydaig** [comment]
@lirantal 0.12 introduced some basic promise support, but I don't think it was fully implemented yet. It wasn't until 0.4 that it became fully implemented. I'll remove bluebird tomorrow and see if it still works in 0.12.

**Comment by ilanbiala** [comment]
@codydaig `assert`, `async`, and `fs-extra` aren't used at all right now for tests, right?

**Comment by codydaig** [comment]
@ilanbiala Correct.

**Comment by lirantal** [comment]
I was actually planning to use async for one of the tests I am working now in the area of the seeddb re-factoring. Why were you asking @ilanbiala ?

**Comment by ilanbiala** [comment]
@lirantal I just removed all the unused ones for now. Why do you need async?

**Comment by lirantal** [comment]
@ilanbiala I can consider using q/bluebird but since we aren't yet focused on what we want to do there let's just leave async to use. I need it because I'm planning to refactor the way the seeddb works so it is testable and with the current async nature there of the db calls it'll be ugly to just wrap everything into callbacks.

**Comment by codydaig** [comment]
@lirantal Async can still be used in the main project, I think @ilanbiala Is talking about the generator. Is there anywhere in the generator specific code that you use async?

**Comment by lirantal** [comment]
Nope.

**Comment by ilanbiala** [comment]
@lirantal if Bluebird offers the same functionality, I think we should just use Bluebird for everything as much as we can. I believe it is faster compared to async.

**Comment by lirantal** [comment]
@ilanbiala I'm ok with moving out of async although are there reasons why you think Bluebird is better than Q (except for performance)

**Comment by ilanbiala** [comment]
Not sure about the differences, but I've been using Bluebird because it's relatively clean and performant.

**Comment by lirantal** [comment]
Ok, well I'm not against Bluebird it's just that Q is very common on the frontend side so it would be ideal to converge into one framework.

**Comment by ilanbiala** [comment]
Closing in favor of #115
