### ISSUE TITLE
Error running yo meanjs on Win

### ISSUE THREAD

**Issue by jjduarte** [meanjs/generator-meanjs#118]
Hi, please anyone can help me to deal with this? 

You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.0
0.4.0
? In which folder would you like the project to be generated? This can be changed lat
Cloning the MEAN repo.......

Error: Command failed: C:\Windows\system32\cmd.exe /s /c "rm ./mean/package.json"
'rm' n?o ? reconhecido como um comando interno
ou externo, um programa oper?vel ou um arquivo em lotes.

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__
 ´   `  |° ´ Y `

PS C:\Users\João Paulo\Documents\local\teste\mean> yo --version
1.4.8
PS C:\Users\João Paulo\Documents\local\teste\mean> npm info generator-meanjs version
0.4.1
PS C:\Users\João Paulo\Documents\local\teste\mean> npm info npm version
2.14.3
PS C:\Users\João Paulo\Documents\local\teste\mean>

**Comment by ilanbiala** [comment]
@codydaig I didn't pick up on the fact that `rm` doesn't exist on Windows. I'll probably convert the generator to use Yeoman/another fs abstraction to to work with files.

**Comment by mleanos** [comment]
@ilanbiala I'm on Windows 7, and the generator works perfectly for me.

**Comment by ilanbiala** [comment]
@mleanos does the command `rm` exist in Windows 7?

**Comment by mleanos** [comment]
@ilanbiala Not typically.. I do have cygwin installed, which has `rm` 

So you're right... this is an issue on Windows.

**Comment by tmfahall** [comment]
Is there a work around we could use until fixed?

**Comment by ilanbiala** [comment]
@jjduarte @mleanos can you replace the index.js file contents with the contents from this Gist: https://gist.github.com/ilanbiala/87d5b8526b78039c64af

Let me know if that works.

**Comment by mleanos** [comment]
@ilanbiala No errors were reported, and the repo was cloned correctly. However, the install quits without any messages after the clone. No prompts are launched, and the name prompt input doesn't make it to `package.json`. So it appears it just stops everything after the clone. 

The clone looked perfect though. No issues with that.

**Comment by wesgen** [comment]
I am tryinig to run it using powershell on windows and I get the same 'rm' not recognized ..
I installed cygwin and I tried running it it passes that point however it just hangs at "this may take a couple minutes"..during that time I am unable to browse to any website and after a while I would see a bunch of errors when trying to download the packages that it could be a proxy issue but I'm not behind a proxy.

I also tried copying the contents from the gist @ilanbiala and it clones but nothing happens after. It quits as @mleanos says and I'm back to the powershell prompt

**Comment by ilanbiala** [comment]
@mleanos it doesn't log anything either?

**Comment by mleanos** [comment]
@ilanbiala No logs, and no errors.. no output whatsoever. Just stops right after the clone, and it appears the clone doesn't run into any issues.

**Comment by sand338** [comment]
I am facing the same issue. Tried it on two different computers but the result was the same. Cloning was successful but I run into 
Error: Command failed: C:\Windows\system32\cmd.exe /s /c rm /package.json
rm is not recognized as an internal or external command

**Comment by tpt22133** [comment]
you should install git on windown 7 and select folder you want . click -> right mouse -> Git Bash
after type command : "yo mean" and everything will good

**Comment by sand338** [comment]
@tpt22133 that worked for me
- Installed git
- right clicked inside my project folder
- selected "Git Bash Here"
- entered "yo meanjs"

Thank you.

**Comment by brunobritoapps** [comment]
@tpt22133  Thanks... that worked for me too

Installed git
right clicked inside my project folder
selected "Git Bash Here"
entered "yo meanjs"

**Comment by GiankOtarola** [comment]
@tpt22133 Perfect solution. Working in Windows 10.

**Comment by joehoppe** [comment]
On Windows 7, tried the "git bash here" workaround, but I can't use the arrow keys to navigate to 0.4.1. The arrow keys just don't move the cursor. So I couldn't install 0.4.1. Had to use 0.4.0.

**Comment by hiteshdevlpr** [comment]
Thanks a ton @tpt22133  worked for me too.

**Comment by Yording** [comment]
Hi @joehoppe,¿ Could you navigate with arrow keys?

**Comment by Yording** [comment]
I can not navigate with the keys flechas.¿any solution?

**Comment by mukeshmk** [comment]
Hi, I need some help here.
I am running a Win 10 PC, I have installed MEAN Stack. and when I run the "yo meanjs" command in the terminal, I am getting the following error msg:

![capture](https://cloud.githubusercontent.com/assets/7903100/12429410/18f0633c-bf10-11e5-8a5e-3daaf397b4e0.PNG)

I have even tried using the "Git Bash" here option suggested here, it didn't work for me, but the above error didn't pop up but still the "install" part kept going for over 2 hours. (Which I then had to cancelled cause I had other work)

Note:
-I have installed python 2.7.7, Microsoft Visual C++ and Node.js
-I have also followed these command in admin mode in my cmd.
--npm install -g bower
--npm install -g grunt-cli
--npm install -g yo
--npm install -g generator-meanjs

Please help me out.
Thank You :)

**Comment by GiankOtarola** [comment]
@mukeshmk if you have installed git on your Win 10, run "yo meanjs" in git bash console.

**Comment by mukeshmk** [comment]
@GiankOtarola i tried that, and I have mentioned in my comment above, that the installation took me over 2 hours and there was no progress.

Is there any other way that i can solve this ?
