### ISSUE TITLE
is this still alive? could anyone refer me to any place where i can find a roadmap or something similar? thankyou

### ISSUE THREAD

**Issue by gustavomick** [meanjs/generator-meanjs#122]

**Comment by lirantal** [comment]
@gustavomick the generator is definitely still alive.
@codydaig and @ilanbiala are doing the work to make the generator compatible with our latest version of meanjs.

It is already compatible and working with latest version v0.4.2 of meanjs, but the npm repository is not yet up to date AFAIR.

**Comment by codydaig** [comment]
@gustavomick @ilanbiala The npm repository is up to date. However, we're lacking the sub generators in the latest version.

**Comment by lirantal** [comment]
Ahh glad to hear we got it working finally.

**Comment by vko-online** [comment]
Generator doesn't work

**Comment by gustavomick** [comment]
@lirantal thnx,

- may be because i'm new to this i thought generator/scaffolding were core. arent?
- i didnt easily find a matrix of internal features / libraries that were included and why. (maping libs to common requirements are resolved .. like how auth is resolved, localization, caching, tasks included etc). 
- i didnt find a roadmap / goals and rough estimated dates. (ex angular2, react, new features)

sorry if im asking too much but and this is trivial for experts .. but im not.. so im asking because i like community (your) work and i really want to use it as a way to implement these techs in my projects and share them with my team .. and because of this i need higher visibility than i have found. 

thanks again

**Comment by lirantal** [comment]
@vko-online the generator for 0.3.x should work just fine.
Why do you say it doesn't exist?

**Comment by vko-online** [comment]
`yo meanjs:crud-module test` initializes new project, before (for mean 0.3.x) it generated crud-module. Something weird is going on, take a look at master branch, it doesn't have any module generator thing, just app, and there is no branch for 0.3.x

**Comment by ilanbiala** [comment]
@vko-online there are no subgenerators,. If you want to use 0.3.x install a previous version of the generator. We will release subgenerator support soon.
