### ISSUE TITLE
generator generate only project

### ISSUE THREAD

**Issue by zloyded** [meanjs/generator-meanjs#123]
Hi all!
Generator generate only project and ignoring any parameters, generate model, generate crud, etc.
Example:

``yo meanjs:angular-module Tralala``
``What mean.js version would you like to generate?``
`` > 0.4.0 ``
 `` 0.4.1 // select any ``
`` ? In which folder would you like the project to be generated? This can be changed later. (mean)``

no chances to generate something else other than the project itself

**Comment by fungxu** [comment]
Yes, It's still in development.

**Comment by mbonig** [comment]
Do you know what it is that is broken? Perhaps with some additional information one of us can generate a pull request that would resolve it.

**Comment by ilanbiala** [comment]
We have no subgenerator support as of now. This will be added soon.

**Comment by mbonig** [comment]
I would like to help support the sub-generators. So that I can be quicker about it, any information you have on what broke between .3 and .4 would be helpful.

**Comment by codydaig** [comment]
@mbonig The biggest difference between .3 and .4 is the folder structure.

**Comment by kbowerma** [comment]
@ilanbiala it would be nice if you updated the readme and stated that you pulled the sub generators out.  I just spent a half hour trying to figure out why they didn't work which included watching a youtube video.   Had it not been for this issue I would have still been trying.

**Comment by ilanbiala** [comment]
@kbowerma https://github.com/meanjs/generator-meanjs/blob/master/README.md#application-generator read the bottom of that section.

**Comment by vko-online** [comment]
Any chance to use/find 0.3 version? My old project still uses mean 0.3

**Comment by ilanbiala** [comment]
@vko-online install an old version of the generator.

**Comment by vko-online** [comment]
@ilanbiala you always keep writing that, but there is no good way to install older version, there is only master branch, no tags, no releases, currently installing with
`npm install -g https://github.com/meanjs/generator-meanjs.git#d3d1ff78b7b1025ee6aeacf3d409c3a2f9451cfc`
But this is not smart

**Comment by ilanbiala** [comment]
`npm info generator-meanjs`. Pick any version in the array before 0.4.1. @vko-online spend a little more time searching next time for an answer instead of just posting here, this isn't a forum.
