### ISSUE TITLE
Problem with the generator of the dev version

### ISSUE THREAD

**Issue by guiseek** [meanjs/generator-meanjs#126]
Yo generator of the crud module is working with the old structure directory

**Comment by ilanbiala** [comment]
@guiseek please give more details.

**Comment by guiseek** [comment]
![meanjsdirs](https://cloud.githubusercontent.com/assets/5638096/10180727/573ffb2a-66e6-11e5-9a00-15d6839ac268.png)

Green directories were added using yo, but the new release is a different structure, an update of the generator I should know?

**Comment by codydaig** [comment]
mean.js v0.4 doesn't have sub generators yet.

**Comment by guiseek** [comment]
Ok! Thanks @codydaig

**Comment by fouadkada** [comment]
i used
```
npm install -g git+https://github.com/meanjs/generator-meanjs.git#0.4-dev
```

and seems to be a good workaround for now
