### ISSUE TITLE
Installation on OS X 10.11 El Capitan & node 4.1.1 fails

### ISSUE THREAD

**Issue by benmarten** [meanjs/generator-meanjs#129]
I have upgrade to El Capitan and latest node 4.1.1 and get this error:

https://gist.github.com/anonymous/9f92890510f74b272252

Any ideas, whats wrong?

**Comment by ilanbiala** [comment]
El Capitan has not yet been released, I'm sure there are bugs with Node/npm/gyp/nan/<insert any low level package here>.

**Comment by codydaig** [comment]
And we don't support node 4.x yet

**Comment by ilanbiala** [comment]
@codydaig Node 4 passes https://travis-ci.org/meanjs/generator-meanjs

**Comment by codydaig** [comment]
@ilanbiala But the project itself doesnt. https://travis-ci.org/meanjs/mean

**Comment by ilanbiala** [comment]
@codydaig @lirantal `node-gyp rebuild` seems to cause the issue.

**Comment by codydaig** [comment]
@ilanbiala meanjs/mean#922 resolves that issue. However, there are still dependency issues of dependencies failing on Node 4.x

**Comment by jimf2342** [comment]
Hi, I also encountered the compilation errors listed by benmarten, but on OS X Yosemite. I have tried several of the work arounds listed in some of the other bugs/links, primarily installing different versions of the dependencies, but that has not worked out for me.

Any work around suggestions?

**Comment by codydaig** [comment]
@jimf2342 What version of Node are you running?

**Comment by jimf2342** [comment]
@codydaig I encountered this problem with node v4.1.2.

**Comment by codydaig** [comment]
@jimf2342 If you want to use Node 4, you must select master when generating the project. Node 4 support isn't in an official release yet in the meanjs project.

**Comment by jimf2342** [comment]
@codydaig What would you recommend? I'm dipping my toes in the water and I am more interested in a stable version versus managing unreleased versions. Rev node back to an earlier revision and proceed from there?

**Comment by codydaig** [comment]
@jimf2342 Yes. If your looking for stable I recommend Node 0.12.x simply because there's not enough Node 4 support yet. A lot of projects and packages are still working on getting dependencies up to date.

**Comment by jimf2342** [comment]
Thanks @codydaig. I will back down and give it another try.

**Comment by codydaig** [comment]
@jimf2342 I recommend installing node with nvm as it allows you to easily switch between versions depending on your mood. 

http://www.codydaig.me/installing-node-with-nvm/

**Comment by jimf2342** [comment]
@codydaig Thanks for the link! Virtual version management for the win. :)
