### ISSUE TITLE
Unable to generate code using yo and  generator meansjs

### ISSUE THREAD

**Issue by farhatnawaz** [meanjs/generator-meanjs#130]
I am trying to generate code using the meanjs generator with the command "yo meanjs" but it pulls up a lot of errors. I have tried several fixes posted on different blogs, like downgrading to node version 0.12.7 from 4.1 as it solved the problem for some people. But I am still stuck with it. I am attaching a screenshot of the error that I am getting. Any help would be appreciated. Thanks!

node version: 0.12.7
npm version: 2.11.3
yo version: 1.4.8

![screenshot 195](https://cloud.githubusercontent.com/assets/8686962/10202112/b8c015dc-67c8-11e5-8a01-93a982ded1df.png)

**Comment by MichaelGatesDev** [comment]
So, did you try running it with administrator privs?

**Comment by frhtnwz** [comment]
Yes, I did. But it gives the same errors including "try running with administrator prevs"

**Comment by GiankOtarola** [comment]
@frhtnwz I had de same problem and it's been solved with this solution: https://github.com/meanjs/mean/issues/856

1) See in the project folder the .bowerrc file, see the directory location(should be public/lib) and you will see that the lib folder was not created.
2) Create lib folder in public folder.
3) Run in your folder project: bower install 
and then:
 npm install -g bower

**Comment by frhtnwz** [comment]
@GiankOtarola Holy shit! that worked. Thanks so much dude. you're a life savior. I had been struggling for more than two weeks.
