### ISSUE TITLE
express-model not working

### ISSUE THREAD

**Issue by tzeyangng** [meanjs/generator-meanjs#134]
When i tried to run the following, instead of creating the category, it try to create a brand new mean template. 

yo meanjs:express-model category

**Comment by tzeyangng** [comment]
nevermind, just realized the sub command is not develop yet.

**Comment by codydaig** [comment]
@tzeyangng Sorry about that, glad you figured it out though.

**Comment by tzeyangng** [comment]
@codydaig 2 questions:
- in the cross road to select nodejs 4 or older version to start new project. is the current master release stable enough for the main application generation? still expect major changes? Any suggestion?
- when can we expect the sub command to be release? 

thanks.

**Comment by codydaig** [comment]
@tzeyangng We haven't released official Node 4 support, so for stability, I'd recommend using an older version of node (0.12.x). 

We're working on the sub generators, but do not have a current release data.
