### ISSUE TITLE
yo meanjs doesn't work

### ISSUE THREAD

**Issue by farhatnawaz** [meanjs/generator-meanjs#136]
I am trying to create the app folders and files using "yo meanjs" but I am getting an error shown in the picture. Any idea what this is? 
![meanjsyo](https://cloud.githubusercontent.com/assets/8686962/10611006/ac7cf470-7763-11e5-89c3-7d3fce3edbab.png)

**Comment by codydaig** [comment]
@farhatnawaz Unfortunately We don't support Node 4 yet.
