### ISSUE TITLE
meanjs subgenerators with 0.4.0 or 0.4.1

### ISSUE THREAD

**Issue by aladdam** [meanjs/generator-meanjs#137]
Hi,

I am trying to use sub-generators and facing issue.

E.g. when I tried to create angular-module, the prompts are not asking for the module's destination. Rather they are asking for project which eventually failed when I selected current directory of an existing project. Same happened when I tried with "meanjs:crud-module".

Is there anything I am missing here?

PS C:\data\angularjs\tst003> yo meanjs:angular-module events
undefined
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.0
0.4.0
? In which folder would you like the project to be generated? This can be changed later. (mean)

PS C:\data\angularjs\tst003>

**Comment by ilanbiala** [comment]
There are no subgenerators released yet for the new generator. Hold tight.

**Comment by aladdam** [comment]
Is there any way to download load old version and use? Please suggest.

Thanks
