### ISSUE TITLE
Error in yeoman generator 0.4.X

### ISSUE THREAD

**Issue by iasinDev** [meanjs/generator-meanjs#138]
After installing yeoman and generator-meanjs, when executing yo meanjs and answering interactive questions I'm getting:

? Would you like to generate the chat example module? No
   create xmen/package.json
   create xmen/bower.json
   create xmen/config/env/default.js
Running npm install for you....
This may take a couple minutes.
Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:696:13)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:745:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at Pipe.onread (net.js:528:21)
vagrant@vagrant-ubuntu-trusty-64:~$

It's a temporary connection issue, an issue... or connection problem..?

many thanks in advance!

**Comment by ilanbiala** [comment]
I'm not sure where maxBuffer is being exceeded, all I can say is try again, because this seems like an issue that happened during npm install.

**Comment by iasinDev** [comment]
I've tried again 2 or 3 times more and the same :-(  . The thing is that on another virtul machine I have the generator of the previous stable version, I think it's 0.3.0, that works perfect, but I have this error with 0.4.0 0.4.1 and master. I've been searching thr 0.3.0 version without success, there is a way to use this version instead?

**Comment by codydaig** [comment]
@iasinDev I would say this is some soft of enviorment settings. I'm not familiar with vagrant, but I would assume it can only handle x amount in the stdout, and the npm install may be exceeding that. I would try cloning the master branch from meanjs/mean and see if npm install gives you the same issues or not.

**Comment by iasinDev** [comment]
Hi Cody, I've been trying on another computer where I have more memory to alocate, yesterday I tried with a virtual machine with 2048 MB, and today with 4096, but the same result. I keep trying but only seems working under Vagrant the 0.3.0 version. 

Meanwhile, this version is hook on other github? on this one, I only can see 0.4.1 version. 

There is something I can post to solve this issue?

thanks!

**Comment by iasinDev** [comment]
apart from that, I don't see the ascii of yeoman, is it an error?
![screenshot003](https://cloud.githubusercontent.com/assets/12020079/10801153/3f9d991e-7db6-11e5-97fc-8bbec5a1b8b4.jpg)

**Comment by iasinDev** [comment]
And after several minutes I get the previous trace

**Comment by iasinDev** [comment]
Hi again, regarding, http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process

Maybe it's a problem with child_process in app/index.js ? that need to be bigger?

**Comment by ilanbiala** [comment]
@iasinDev maybe. @codydaig thoughts on that? Maybe you can npm link a local clone of the master branch with that change to see if it works?

**Comment by militeli22** [comment]
I have the same problem . anyone found a solution ?

**Comment by ilanbiala** [comment]
@codydaig and I have worked to get rid of many of the bugs in 0.4.1, and today we released 0.4.2. Please try it out and if it resolves your issues, let us know!

**Comment by makzee** [comment]
Hi @ilanbiala, 0.4.2 still has the same issue.

**Comment by militeli22** [comment]
hiii , sorry my english is very bad .

i have solved the Problem. The Problem was the  MongoDB Driver for Windows and Environment Settings.

You Need For Windows :
Visual Studio c++ 2010 (do not use higher versions)
Windows 10 64bit SDK
Python 2.7 or higher

And Kerberos Node Package :
npm install -g node-gyp

repository:
https://www.npmjs.com/package/mongodb

**Comment by codydaig** [comment]
@makzee Does @militeli22's solution solve your problem by chance?

**Comment by jjcad** [comment]
I'm getting the same error as OP using the latest version of the generator running Ubuntu 14.04.  It happens regardless of whether I try to generate with 0.4.0, 0.4.1, or 0.4.2.

**Comment by philipskokoh** [comment]
I have the same problem .
I am using CentOS 7.

```
? Would you like to generate the article example CRUD module? Yes
? Would you like to generate the chat example module? Yes
Running npm install for you....
This may take a couple minutes.
Error: stderr maxBuffer exceeded.
    at Socket.<anonymous> (child_process.js:707:13)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at Pipe.onread (net.js:529:21)
```

**Comment by philipskokoh** [comment]
I found out that it's because of old nodejs and npm version.
I install latest nodejs (v 5.4.0) and npm (v 3.3.12), and `yo meanjs` runs properly now.

**Comment by makzee** [comment]
Thanks @philipskokoh I updated nodejs & npm and it worked.

**Comment by ilanbiala** [comment]
Technically we do not guarantee support for Node v5, so proceed with caution.

**Comment by jeffthompson1971** [comment]
Does not work for me.  Any proper solution out there?
