### ISSUE TITLE
Its taking too long to generate

### ISSUE THREAD

**Issue by Faiz7412** [meanjs/generator-meanjs#141]
I have node v4.2.1, npm v3.3.10, yo v1.5.0.
I had no issues in scaffolding using this generator. However after updating node, npm and yo and reinstalling the generators, it's taking hours and nothing happens. I have had issues with few other generators as well. Is this generator compatible with new version of node?

**Comment by ilanbiala** [comment]
@Faiz7412 we don't yet support npm 3 and yo 1.5. We're working on adding more features to the generator before expanding support to other versions. Help us out with #131 and once we get that going we'll start adding tests. Also, the MEAN repo itself needs to support that stack, and it may have issues with npm 3.

**Comment by ilanbiala** [comment]
@codydaig and I have worked to get rid of many of the bugs in 0.4.1, and today we released 0.4.2. Please try it out and if it resolves your issues, let us know!

**Comment by Faiz7412** [comment]
Still not solved, unfortunately.

**Comment by Faiz7412** [comment]
It took time, but yes I can scaffold now! Thank you so much!

**Comment by ilanbiala** [comment]
@Faiz7412 was there anything in particular that was slow?
