### ISSUE TITLE
So the Sub-Module Generator still not available for v4.1.0?

### ISSUE THREAD

**Issue by SharkIng** [meanjs/generator-meanjs#143]
Reading the Official Doc. There is some command line like "yo meanjs:crud-module test"

However, it seem does not work yet?

In the mean time, what should we do to generate module?

**Comment by edrpls** [comment]
You could probably copy/paste the directory and edit the files as needed or downgrade to 3.*

**Comment by jsantana90** [comment]
how do you downgrade, I did `npm view generator-meanjs versions` and got 
```
[ '0.0.1',
  '0.0.2',
  '0.0.3',
  '0.0.4',
  '0.0.5',
  '0.0.6',
  '0.0.7',
  '0.0.8',
  '0.0.9',
  '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.1.4',
  '0.1.5',
  '0.1.6',
  '0.1.7',
  '0.1.8',
  '0.1.9',
  '0.1.10',
  '0.1.11',
  '0.1.12',
  '0.4.1' ]
```

But no `0.3.x` version

**Comment by codydaig** [comment]
The 0.1.x versions of the generator generate 0.3.x versions of the project.

**Comment by codydaig** [comment]
If your using the 0.3 structure of the project, yes, the sub generators do work

**Comment by SharkIng** [comment]
@codydaig is that mean I still dont have any way to generate a 0.4.1 structure right now?

**Comment by edrpls** [comment]
I'm not @codydaig, but yes. It means that.

**Comment by codydaig** [comment]
@SharkIng The latest generator generates the 0.4 app, but does not have any sub generators.

**Comment by dpranav007** [comment]
any idea by when we can have sub-generators , vertical module creator ?
there was a #0.4-dev branch which allowed vertical module creation , but now breaks with the latest release ?

**Comment by dbelieves** [comment]
i am also waiting for vertical modules.

i feel so helpless at this point of time.
had i known to code at such a good level i would have surely contributed. :|

**Comment by dbelieves** [comment]
also 0.3 is not available now.
stuck.

**Comment by ilanbiala** [comment]
@codydaig and I have worked to get rid of many of the bugs in 0.4.1, and today we released 0.4.2. Unfortunately, it does not have subgenerators and module generators as we are still working on PRs #131 and #145.

**Comment by satyarapelly** [comment]
documentation on meanjs show crud-module subgenerator not working, anybody has working repo, so that pull it??

**Comment by UndeadBaneGitHub** [comment]
https://github.com/meanjs/generator-meanjs/pull/157
All but CRUD and ACL generators are there. CRUD is coming really soon, ACL to follow.

**Comment by codydaig** [comment]
@UndeadBaneGitHub Thanks for hard work and awesome PRs! We'll review them individually and get them merged in.
