### ISSUE TITLE
executing `meanjs:crud-module` runs `meanjs` generator

### ISSUE THREAD

**Issue by csicar** [meanjs/generator-meanjs#177]
After creating an meanjs-application with yo by:
```bash
$: yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? (Use arrow keys)
  master 
  0.4.0 
  0.4.1 
❯  0.4.2 
```
(this is all working perfectly)

When I try to create new module in the app by running ` yo meanjs:crud-module testModule`
yeoman will start the normal `meanjs`-generator. This happens when I am in the `<app>/`-Directory as well as in the `<app>/modules` directory

All dependencies (nodejs, yo, meanjs, ...)  are up to date, so they shouldn't be the issue

**Comment by codydaig** [comment]
The crud-module isn't available yet for the latest version on the generator. We are in the process of moving all the old sub generators over.

**Comment by csicar** [comment]
Is there any way to install the generator for version 0.3.*?
