### ISSUE TITLE
No 0.3.x versions available in npm registry.

### ISSUE THREAD

**Issue by jjcad** [meanjs/generator-meanjs#180]
Checking the versions available in the npm registry, it skips from v0.1.12 to v0.4.1

Are any v0.3.x available somewhere else since that's considered the present stable version according http://meanjs.org/?  Maybe the "Download" button on the front page should also be pointing to the stable version?  That way people who are just trying to use it can go ahead and do so, without having to try and figure out why they can't get the latest development versions to work, or be concerned that the docs for v0.1.12 aren't available either.

http://registry.npmjs.org/generator-meanjs

**Comment by ilanbiala** [comment]
0.1.12 is the 0.3.x generator.

**Comment by jjcad** [comment]
Cool. I'm not sure if there's a way to update or clarify that in the npm registry, but I'd happy to submit a PR sometime this week to help clarify that in the documentation if that's something you'd be interested in.

**Comment by codydaig** [comment]
@jjcad go ahead and submit a PR! The documentation lives at meanjs/meanjs.github.io
