### ISSUE TITLE
yo meanjs:crud-module is not working for generator-meanjs@0.4.1', '0.4.2', '0.4.3'

### ISSUE THREAD

**Issue by eaktadiur** [meanjs/generator-meanjs#195]
You don't seem to have a generator with the name meanjs:crud-module installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 14 registered generators run yo with the `--help` option.

old version are working fine

**Comment by ilanbiala** [comment]
Are you using 0.4.3?

**Comment by eaktadiur** [comment]
yes,

/usr/local/lib
├── bower@1.7.6
├── forever@0.15.1
├── generator-keystone@0.3.13
├── generator-meanjs@0.4.3
├── grunt@0.4.5
├── grunt-cli@0.1.13
├── npm@3.5.3
└── yo@1.6.0

**Comment by ilanbiala** [comment]
try "mean-module"

**Comment by eaktadiur** [comment]
yes, yo meanjs:mean-module customer is working for me. thanks
