### ISSUE TITLE
Unable to generate angular module

### ISSUE THREAD

**Issue by yashgt** [meanjs/generator-meanjs#200]
E:\Projects\trulo>yo meanjs:angular-module trulo
Error meanjs:angular-module trulo

You don't seem to have a generator with the name meanjs:angular-module installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 16 registered generators run yo with the `--help` option.

I have already installed meanjs using:
npm install -g generator-meanjs@0.4.1 --save

**Comment by ilanbiala** [comment]
All the generators listed are folders in the repo: https://github.com/meanjs/generator-meanjs, so we don't have a finalized angular-module generator yet. Also, please install the latest generator version.

**Comment by yashgt** [comment]
So which generator can we use to generate an angular module?
I also tried with latest version.
The online documentation mentions angular-module which does not exist.

**Comment by yashgt** [comment]
If some generators are NOT developed in the new version, is there a way I can obtain them from the EARLIER versions?
The documentation at http://meanjs.org/generator.html is for 0.3.x. It DOES show angular-module as a generator. However, the git repository no longer has the 0.3.x available for download.

It appears as if a new version is release on github without many features of the old version and teh old version is made unavailable.

**Comment by ilanbiala** [comment]
Install version 0.1.x from npm.

**Comment by yashgt** [comment]
Sorry, but I am looking for a later version for which documentation is available. 0.3.x

**Comment by ilanbiala** [comment]
That version on npm corresponds to 0.3.x support in MEAN.

**Comment by rof20004** [comment]
yo meanjs:angular-module not work, now is:

yo meanjs:mean-module

**Comment by nodox** [comment]
Doc should be updated so this and #208 can be closed. Any PR?

**Comment by staminna** [comment]
Can somebody update meanjs.org documentation for this?

**Comment by bellaj** [comment]
from the official website : The Yeoman Generator is currently not maintained. It is based on an older version of MEAN.JS (0.4.2). This content is retained here for historical purposes and for anyone still using the generator on their projects.

**Comment by nodox** [comment]
Close this issue?

**Comment by staminna** [comment]
Is there a new tool for this task if I may ask?

**Comment by lirantal** [comment]
Sorry but no new generator.
You should clone the main `meanjs` repo and use it as a starting point.
