### ISSUE TITLE
crud-module generator issues

### ISSUE THREAD

**Issue by vinayakvinay** [meanjs/generator-meanjs#203]
Hello Cody,

I have the latest version of node installed in my machine (5.x of node, 3.x of npm). After facing lot of issues with the latest node version I downgraded to 0.12.x of Node and 2.x of npm.

My mean-generator version is 0.4.3. I can't use both crud and vertical module generators.

I using older version of Node and NPM where my other packages require newer version of node and npm.

Please suggest me which of the node and npm version works fine (higher than 0.12.x) to use all the features of generator-meanjs.

**Comment by rof20004** [comment]
You need to wait the pull with corrections->https://github.com/meanjs/generator-meanjs/pull/201

About vertical module generators, did you tried: yo meanjs:mean-module ?

angular-module not exists anymore and mean-module create all the struct client and server.

**Comment by vinayakvinay** [comment]
yo meanjs:mean-module - only creates the folder structures. How to use CRUD module/Vertical module?

When I tried crud module generator I got the following error message:

Error meanjs:crud-module xmen 

You don't seem to have a generator with the name meanjs:crud-module installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 14 registered generators run yo with the `--help` option.

**Comment by rof20004** [comment]
I said to you, #201 

Wait for merge and then update your generator with npm.

**Comment by vinayakvinay** [comment]
Thanks for the note. Can I work with latest version of Node or should I stay with older 0.12.x version?

**Comment by rof20004** [comment]
Yeah, you can update.

**Comment by vinayakvinay** [comment]
I just want to utilize all the feature of meanjs generator such as CRUD modules and Angular sub generators. Please let me the system requirements. I prefer to use latest version but I can't work with mean generators with latest node realeases.

Node - 5.x latest stable
Npm - 3.x latest
generator-meanjs - ?? (Please suggest me the latest working version of generator)

**Comment by rof20004** [comment]
$ npm install generator-meanjs@latest

With this command (@latest) you always get the last version of any package.

**Comment by vinayakvinay** [comment]
What about the Node version?

**Comment by vinayakvinay** [comment]
What is the latest working version of Node with meanjs generator?

**Comment by rof20004** [comment]
I do not know, my packages are updated, then I always use the latest version, if you want to update node, you can do with npm install -g n, after in terminal use n stable, then link the newer version to your node executable path.

**Comment by codydaig** [comment]
The generator should work with Node v5, however, the latest version that I've personally tested it with is v4. The PR has been merged for the crud-module, but it's in the queue to be published, so it's not available on NPM yet. You can follow #204 for the status of the publish.

**Comment by vinayakvinay** [comment]
Thanks for the note @codydaig
