### ISSUE TITLE
inconsistent code in CRUD module generator views

### ISSUE THREAD

**Issue by hfournier** [meanjs/generator-meanjs#206]
The form view uses ng-, but the other two views data-ng-. As a generator, the coding should be consistent throughout.

**Comment by codydaig** [comment]
In 0.4, we removed the data-. Can you point out where there is remaining `data-`'s?

**Comment by hfournier** [comment]
generator-meanjs / crud-module / templates / client / views / 
_.list.client.view.html 
_.view.client.view.html

**Comment by codydaig** [comment]
#207 Addresses this issue.
