### ISSUE TITLE
run app on different ENV?

### ISSUE THREAD

**Issue by zenithtekla** [meanjs/generator-meanjs#213]
Hello,
I'm new to your scaffold package.
What are the grunt and gulp commands for triggering/running the deployed app in development, test, and production modes?
and where to configure development environment?
On a side note: I like gulp better. 
Thanks

**Comment by codydaig** [comment]
@zenithtekla The README on the main repo outlines most of the gulp and grunt commands. We are currently working on switching over to gulp, but currently both are working. https://github.com/meanjs/mean
