### ISSUE TITLE
'generator-meanjs' is not in the npm registry

### ISSUE THREAD

**Issue by rclogs** [meanjs/generator-meanjs#223]
I tried installing mean generator using  `npm install -g generator-meanjs` command. but it gives following error. 

npm ERR! Darwin 15.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "generator-meanjs"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E404

npm ERR! 404 no such package available : generator-meanjs
npm ERR! 404
npm ERR! 404 'generator-meanjs' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by ilanbiala** [comment]
https://www.npmjs.com/package/generator-meanjs

**Comment by codydaig** [comment]
@rclogs I just ran that command on my machine that didn't have it installed and it worked just fine. Not sure what was/is going on for you but this would be an issue with npm, and not the generator-meanjs repo.

**Comment by codydaig** [comment]
Feel free to reopen if your still experiencing issues.

**Comment by rclogs** [comment]
Its Works.. !! Not sure why the issue was coming before
