### ISSUE TITLE
Error while running yo meanjs command.

### ISSUE THREAD

**Issue by kushalmahajan** [meanjs/generator-meanjs#224]
Hi, 
Everything installed for me fine. But when I run yo meanjs command, it gives me an error

**Error: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git --version"
'git' is not recognized as an internal or external command,
operable program or batch file.**

**Comment by ashavidyadharan** [comment]
Install [git](https://git-scm.com/downloads) and set the installed path in environment variable

**Comment by codydaig** [comment]
@kushalmahajan Yup. You need git installed and need to run the command fro the git bash client. Let us know if you still have issues.

**Comment by abdulqadeerel** [comment]
is Git must be installed in order to run this command, even If I dont' want to report usage statistics ?????
