### ISSUE TITLE
Add generator option to scaffold application without oauth logins

### ISSUE THREAD

**Issue by water42** [meanjs/generator-meanjs#227]
I'm building a relatively simple application that does not require oauth logins, but does require an advanced administration and users system which Meanjs provides, and it's been a somewhat arduous process refactoring the code to remove the oauth functionality.

This is just a suggestion to make the app a bit more flexible. Thanks for the work you guys have done on this.

**Comment by codydaig** [comment]
@water42 This should go on the main meanjs/mean repo, this repo only serves as the generator. As for stripping out oauth, in theory, you can remove the users module and replace it with your own if you don't like the way that it is structured.

**Comment by jcsaladin** [comment]
Hi, if i delete the user folder, the project does not start

**Comment by ilanbiala** [comment]
Can this issue be closed?
