### ISSUE TITLE
Mean generator not available

### ISSUE THREAD

**Issue by shibilikr** [meanjs/generator-meanjs#229]
This is the response I get when I try to install mean generator

sudo npm install -g generator-meanjs
npm http GET https://registry.npmjs.org/generator-meanjs
npm http 200 https://registry.npmjs.org/generator-meanjs
npm http GET https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm http 200 https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm http GET https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm http 200 https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm http GET https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm http 200 https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/generator-meanjs/-/generator-meanjs-0.4.4.tgz
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "generator-meanjs"
npm ERR! cwd /Users/shibili/testnode
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ENOSPC
npm ERR! errno 54
npm ERR! Error: ENOSPC, write
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

**Comment by codydaig** [comment]
@shibilikr We no longer support Node v0.10.
