### ISSUE TITLE
How can I safely remove a CRUD module

### ISSUE THREAD

**Issue by AttilaSATAN** [meanjs/generator-meanjs#23]
How can I safely remove a CRUD module? Is enough to just delete the folder and server files?
I've also asked this question on stackoverflow.

http://stackoverflow.com/questions/23781750/how-can-i-safely-remove-a-crud-module

**Comment by manojsanjeewa** [comment]
- [ ] 

sdasdadad

asd

asdas# asdasda##asdasdad

**Comment by manojsanjeewa** [comment]
asdasdasd

**Comment by sebakc** [comment]
I just delete it  and never had any problems .
