### ISSUE TITLE
forgot password / nodemailer doesnt work when deployed in heroku

### ISSUE THREAD

**Issue by KartheekJavvaji** [meanjs/generator-meanjs#235]
I have tried changing the service form gmail to outlook too. It works locally both in gulp and gulp prod. Should we change ALLOWED_HOSTS like thingy. I cannot find this option anywhere.
Failed to load resource: the server responded with a status of 400 (Bad Request) is being loaded in the console. Do i need to change the .gitignore . I have also removed pubic/dist from the .gitignore.

**Comment by KartheekJavvaji** [comment]
I figured out the problem. It was with the nodemailer version. Just change the version in the package.json to 2.4.2 and it works just fine.

**Comment by nidhalmesselmani** [comment]
I did that, still doesn't work

**Comment by KartheekJavvaji** [comment]
Are you sure you upgraded the node mailer version?.... And check your mail once for mails regarding blocking access due to new location.
