### ISSUE TITLE
mean (master) grunt error!

### ISSUE THREAD

**Issue by TigerBui** [meanjs/generator-meanjs#236]
![ice_screenshot_20160706-104631](https://cloud.githubusercontent.com/assets/1240681/16607017/1b88419c-4367-11e6-846a-8506bc7fe1bf.png)

**Comment by steventj** [comment]
What's the errors?
I don't see any errors. 
Only warning, which is fine enough.

**Comment by codydaig** [comment]
@TigerBui Those are all warnings. I'm closing this. Feel free to reopen if you can show any errors that are occuring.

**Comment by TigerBui** [comment]
Thanks @codydaig and sorry!

**Comment by codydaig** [comment]
@TigerBui No Worries!
