### ISSUE TITLE
npm i "--only=dev" error!

### ISSUE THREAD

**Issue by TigerBui** [meanjs/generator-meanjs#239]
![ice_screenshot_20160713-112652](https://cloud.githubusercontent.com/assets/1240681/16791962/f5ab3664-48ed-11e6-8493-0f34c6472b7a.png)

**Comment by ilanbiala** [comment]
@TigerBui do you still have this error?

**Comment by TigerBui** [comment]
@ilanbiala Yes! i still haven't find this error!

**Comment by ilanbiala** [comment]
The error seems like it's saying a package is improperly installed, but I'm not positive. @codydaig any ideas?

**Comment by TigerBui** [comment]
Thanks @ilanbiala commented 😄
