### ISSUE TITLE
Remove deprecated `require.extensions`

### ISSUE THREAD

**Issue by matthewrankin** [meanjs/generator-meanjs#24]
According to the [Node.js v0.10.29 Manual][require.extensions], `require.extensions` has been deprecated. Given this, it seems like it would be a good idea to remove the `require.extensions` used in `config/init.js`.

[require.extensions]: http://nodejs.org/api/globals.html#globals_require_extensions

**Comment by yokodev** [comment]
Hi,  I'm looking for an option to remove this from the original MEAN shell,  
    
  require.extensions['.server.controller.js'] = require.extensions['.js'];
    require.extensions['.server.model.js'] = require.extensions['.js'];
    require.extensions['.server.routes.js'] = require.extensions['.js'];  


 I'm using node 4.5 and trying to get rid of this. Any ideas how to go about doing this? 
Thanks

**Comment by ilanbiala** [comment]
@yokodev can you point to where this is in the latest master?

**Comment by yokodev** [comment]
No, sorry for the confusion...  I'm trying to update a MEAN project which is based of an old version around 2014 and so I was looking for a "best practice" way to achieve this. Any advice on how to do this is really appreciated. 
Thanks

**Comment by ilanbiala** [comment]
2014 is pretty outdated code, so you might be better off starting a new project and migrating your code manually.

**Comment by yokodev** [comment]
@ilanbiala  I know, that's the problem... The project at this phase is in no condition of restarting from scratch it has so much work add it, so What I've done so far is just, got rid of those 3 lines and added the 
server.controller, model and  routes to each needed file (there were not that many) so anyway. That's my update.

**Comment by ilanbiala** [comment]
👍
