### ISSUE TITLE
node_modules uninstall not working

### ISSUE THREAD

**Issue by seshaljain** [meanjs/generator-meanjs#248]
Not sure if this is a Node or Generator problem, but whenever I try to use the command:

`for node in``ls node_modules``; do npm uninstall $node; done;`,

it simply keeps on repeating this message:

> for node in `ls node_modules`; do npm uninstall $node; done;
> npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
> npm WARN mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
> npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
> npm WARN mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
> [..................] - normalizeTree: sill install loadCurrentTree

Now I don't know how to delete these ~875 dependencies.
(Windows shows error: file path is too long or something, so I use the above command via Git Bash, it works quite well for other node projects)
OS: Windows 10;
NPM: 3.10.6;
Node: 4.4.6;
generator-meanjs: 0.4.2;

Tried doing things like restart and install somewhere else, but the problem persists, so probably it isn't a permissions issue.

I am new to MEAN.js and Node.

Thanks in advance!

**Comment by ilanbiala** [comment]
Do you still have this issue? It might have been a temporary dependency conflict from one of our dependencies.
