### ISSUE TITLE
angular-modules working locally not working on heroku

### ISSUE THREAD

**Issue by smokeyblues** [meanjs/generator-meanjs#253]
I built two new angular modules into my project with:
`yo meanjs:angular-module <module-name>
and they work great locally but when I pushed the project with the new modules to heroku the same routes trigger the 'not-found' state and nothing shows up in the heroku logs.

**Comment by mleanos** [comment]
@smokeyblues How do you attempt to navigate to these routes when getting the 'not-found'? Do you have menu items in the navigation?

If no aspect of your new angular modules are reflected in your Heroku deployment, then my guess is that the new angular modules have not been minified before deploying.

**Comment by smokeyblues** [comment]
Thanks @mleanos I think you are right. There are no references to the about or contact modules in application.min.js. So what's the best way to re-minimize the project? Should I write and run a new grunt script to uglify the new modules and cut/paste them into application.min.js or is there a better way to push changes to production?

**Comment by mleanos** [comment]
You can use the `gulp build` or `gulp prod` tasks to rebuild the *public/dist* folder; this will minify the project again.

**Comment by smokeyblues** [comment]
Oh yeah that's right. I kept thinking I needed to use grunt. That resolved my issue. Thanks so much!
