### ISSUE TITLE
Logout should not use GET

### ISSUE THREAD

**Issue by dalelotts** [meanjs/generator-meanjs#256]
Browsers will pre-fetch pages they "think" you will visit next, having logout be a GET can have quite unexpected side effects. It's not a huge problem for the end user, because you wouldn't lose any information, but it could get annoying.

Consider using POST or DELETE verbs.

**Comment by codydaig** [comment]
@dalelotts Thanks! Do you mind opening this issue in the main repo where this is generated from? github.com/meanjs/mean

**Comment by ilanbiala** [comment]
Can this be closed?
