### ISSUE TITLE
A valid Gruntfile could not be found. Please see the getting started guide for more information on how to configure grunt: http://gruntjs.com/getting-started Fatal error: Unable to find Gruntfile.

### ISSUE THREAD

**Issue by am-firnas** [meanjs/generator-meanjs#275]
It was working fine.But now it's showing this error. Then when I look in the project folder the grunt file is removed automatically, I guess.

  
![11](https://cloud.githubusercontent.com/assets/13057271/26834711/b270e494-4af3-11e7-8b70-92bdbf042897.png)

**Comment by corem96** [comment]
This same error is happening to me, I cannot run grunt command and start my app because of this error and the Grunfile.js is not in root folder.

**Comment by mleanos** [comment]
Grunt was removed from the upstream *mean* project. We have moved to solely using Gulp. The tasks in the `gulpfile` are robust and should provide the tools you will need to run the app.

Closing.
