### ISSUE TITLE
Prevent module generator from pluralizing module name?

### ISSUE THREAD

**Issue by everythingspirals** [meanjs/generator-meanjs#30]
The name of my module is already plural but it does not end with an 's', yet when I generate it, yeoman prepends an 's' to everything. How can I disable this?

**Comment by flipjs** [comment]
Is it possible to add/update the dictionary to include a pair of singular/plural words? For example, 'lens/lenses' . Running 'yo meanjs:crud-module lens' will generate len/lens, which is incorrect.

**Comment by ilanbiala** [comment]
@everythingspirals can you provide the specific word/words you are working with?

**Comment by flipjs** [comment]
Actually I don't have a list. I am working on a camera-related app where lens is singular and lenses is plural. The documentation advises to use 'singular' name when creating crud-module, which is what I did. Or maybe I should have tried the plural name 'lenses' instead?

**Comment by IVLMediaInc** [comment]
I agree with this as well. Pluralization shouldn't be automatic. It's been an annoyance, to say the least. Please remove it.
