### ISSUE TITLE
Using generator only for Client

### ISSUE THREAD

**Issue by macrigiuseppe** [meanjs/generator-meanjs#41]
Your generator is simply amazing. The most complete one with best practice approaches across the entire stack.

Do you think it would be possible to use your generator to create only a client application with angularJS?

Thank you again for the outstanding work.

**Comment by keithics** [comment]
@macrigiuseppe I was actually thinking of the same thing. 
but I did went to generator-angular instead because of time constraint. you are right, I love the best practice approaches with meanjs.
