### ISSUE TITLE
Changes to index.html gives unable to connect after reload

### ISSUE THREAD

**Issue by GCinellu** [meanjs/generator-meanjs#56]
When making any change or just saving the index.html page, after reloading I get 'Unable to Connect',and I manually have to refresh the browser. Nothing destructive, just a small detail.

**Comment by NeverOddOrEven** [comment]
@GCinellu sorry for the delay. Do you mean that livereload is not working? If I am off base, can you provide more context surrounding the problem you are/were seeing?
