### ISSUE TITLE
lots of errors on new generated stack

### ISSUE THREAD

**Issue by thedug** [meanjs/generator-meanjs#57]
I ran yo meanjs and then ran grunt.

vagrant@vagrant-ubuntu-trusty-64:~/app/yo/meanjs$ grunt
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "mocha-test.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'socket.io'

Running "jshint:all" (jshint) task
>> 55 files lint free.

Running "csslint:all" (csslint) task
>> 2 files lint free.

Running "concurrent:default" (concurrent) task
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "uglify.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "cssmin.js" tasks...ERROR
>> Error: Cannot find module 'pako/lib/zlib/messages'
Loading "mocha-test.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "mocha-test.js" tasks...ERROR
>> Error: Cannot find module 'escape-string-regexp'
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'socket.io'

Running "watch" task
Waiting...
Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'socket.io'

**Comment by nanuuki** [comment]
@thedug Are you using the default Vagrant synced folders? The default is painfully slow for me as well on a similar laptop. Switching over to NFS made things run a bit faster but for some reason Grunt did not detect file changes fast enough - it might take up to 30 seconds for a refresh while serving. I migrated to using Samba and everything runs quicker now and file changes are detected nearly instantly by Grunt.

**Comment by thedug** [comment]
@nanuuki I got it working. The issue was that npm was silently refusing to install things globally. This meant that I was using old versions of everything without realizing it. 

As for Vagrant yes I've seen slowness. In fact some grunt tasks are very slow. SMB is only available for windows. :(

**Comment by koonan** [comment]
You can install Samba manually and setup a share for your dev files (/var/wwwfor example) and connect to that, works on OS X too :) your files won't be available while your VM is offline though, but IMO that's a small price to pay for the performance gain.

**Comment by NeverOddOrEven** [comment]
If there is a Vagrant/NodeJS issue with Samba/SMB etc... may I suggest a new issue with a better suited title for better clarity and discover-ability.

If the immediate issue is resolved, I would rather this topic be closed. Are you good now @thedug?

**Comment by thedug** [comment]
@koonan I use an ide in osx to edit files. So I that would be a deal breaker.

**Comment by thedug** [comment]
@NeverOddOrEven  Yes. Sorry about the conversation.

**Comment by NeverOddOrEven** [comment]
No worries @thedug, just prefer separate issues to be easily searchable/scannable for myself and others
