### ISSUE TITLE
space and tabs both used for indent

### ISSUE THREAD

**Issue by quocvu** [meanjs/generator-meanjs#60]
We have mixed of tabs and spaces.  I can fix it but would like to know what is the correct/expected style?
I see tabs, 2 spaces, 4 spaces in css, html, and js file.  What do we want it to be?

Thanks

**Comment by lirantal** [comment]
I'm voting for 2 spaces but we need more input from the rest of the devs.

**Comment by nanuuki** [comment]
+1 for 2 spaces

**Comment by NeverOddOrEven** [comment]
I support tabs, somewhat intrinsically due to the above comments. If your preference is that a tab represent two, three, four, etc... spaces, you can configure it locally. Either way, mixing them is not ideal, and we probably need a C.I. rule to enforce formatting.

**Comment by quocvu** [comment]
I also like 2 spaces. That seems to be the de facto standard nowadays.
In some files, I see the mix up with the file itself.

**Comment by ilanbiala** [comment]
I like tabs each 2 spaces.

**Comment by lirantal** [comment]
not tabs, spaces.

@roieki and @amoshaviv 
can we go ahead and re-refactor everything to 2 spaces?

**Comment by ilanbiala** [comment]
@lirantal most developers strongly support tabs, is there any reason we should go with spaces?

**Comment by quocvu** [comment]
* a nice debate at <http://jarrodoverson.com/blog/spaces-vs-tabs/ with a cool visualization
* a good collection of opinions <http://c2.com/cgi/wiki?TabsVersusSpaces>

**Comment by lirantal** [comment]
@ilanbiala you may use the TAB key, but are you really up for using tab controls for code?

**Comment by NeverOddOrEven** [comment]
@lirantal When multiple developers are involved, I do prefer tabs because then a developer may set their preference for amount of spacing a tab visually represents. Per my comment on the other thread, and stated preference above (for tabs), I don't care how we go forward as long as it is consistent.

**Comment by quocvu** [comment]
What is the final word?

**Comment by ilanbiala** [comment]
@quocvu Right now 3 people voted for 2 spaces, and 2 people voted for tabs. I don't think we should make a decision based on 5 votes, so I think we should hold off.

@lirantal what do you mean by "using tab controls for code"? I think @NeverOddOrEven made a very good point in favor of working with tabs.

**Comment by lirantal** [comment]
I mean:
1. We all use the TAB key on the keyboard
2. The TAB key generates spaces and not a TAB control character
3. These spaces should be 2 spaces in length

**Comment by quocvu** [comment]
@ilanbiala @NeverOddOrEven I agree w/ you on the benefits of tabs. But spaces has lots of benefits to. 

15 years ago, 95% of us think tabs is way to go and we wouldn't even have this conversation. Now the tide has shifted and I would guess it's closer to 50-50%.

Spaces allowed me to adopt certain coding style that wasn't possible with tabs and I was okay to give up the flexibility that you mentioned for tabs.

I invite you to read the opinion of some prominent figures who are advocating for spaces. They can describe it better than I can.

* Guido <https://www.python.org/dev/peps/pep-0008/>
* Joel <http://discuss.fogcreek.com/joelonsoftware/default.asp?cmd=show&ixPost=3978>
* Atwood <http://blog.codinghorror.com/death-to-the-space-infidels/>
* Zawinski <http://www.jwz.org/doc/tabs-vs-spaces.html>

Cheers

**Comment by miguelcoba** [comment]
Tabs, please. And each developer can/will/need to configure how he wants to transform that tab char to visual spaces (leave it as tab, change it to 2 spaces, change it to 4 spaces)

**Comment by dotch** [comment]
I vote for 2 spaces, simply because a lot of projects went this way.
angular and express use this indentation style.
since most people don't really care and many pull requests come in using two spaces indentation and would have to be reformatted to tabs, going with 2 spaces seems to be the most convenient way to handle this for everyone.

**Comment by lirantal** [comment]
I'm all for 2 spaces too ;)

**Comment by AlexisTM** [comment]
**Unified**! Tabs or two spaces, but **unified**

**Comment by quocvu** [comment]
Can we have a closure on this?  Anything is better than the mixed style we have today.

**Comment by jloveland** [comment]
+1 for 2 spaces
