### ISSUE TITLE
How to download the 0.4-dev generator?

### ISSUE THREAD

**Issue by flipjs** [meanjs/generator-meanjs#62]
I am using the meanjs 0.4.0 branch, and currently my generator installed on my mac is 0.3 generator. How can I switch to use the 0.4-dev generator. I know its not stable yet, but I hear the crud-vertical-module generator seems to be working fine. So I just want to use it to generate my crud module. Thanks.

**Comment by ilanbiala** [comment]
`npm install meanjs/generator-meanjs#0.4-dev` should work for you and should install the 0.4-dev branch.

**Comment by flipjs** [comment]
It works! Many thanks ilanbiala!

**Comment by drom296** [comment]
This no longer seems to work. I get the following message:

```
no matches found: meanjs/generator-meanjs#0.4-dev
```
