### ISSUE TITLE
Generator for installing bootstrap-SASS with compass

### ISSUE THREAD

**Issue by mohanlate** [meanjs/generator-meanjs#74]
What is the best way to replace the default bootstrap less with the sass port and make it work with compass? Do I have to manually update everything including gruntfile.js?

**Comment by davestacey** [comment]
You probably saw the fork https://github.com/CognitiveScale/meanjs-template , https://github.com/frederik/mean/commit/6e2db3b1a8b7050df4932605339ecc08b9467056  It's not Compass (Libsass) so it may not fit your needs. I also found this article helpful but it is a manual process "Generating CSS into MEAN.JS using Sass" http://ifrederik.com/blog/2014/06/generating-css-into-mean-js-using-sass/  Hopefully we can get a yo generator for this.
