### ISSUE TITLE
"bower install" is not automatically run

### ISSUE THREAD

**Issue by emartinpi** [meanjs/generator-meanjs#75]
I was just trying the generator-meanjs. After downloading the code and run `grunt`
a blank page is shown, so i was wondering what's going on? when you take a look at the code you realize something is missing...
```
bower install
```
It could be great the generator do it for you as it does `npm install`

**Comment by davestacey** [comment]
I also found it useful to run "grunt build" or NODE_ENV=production grunt build" to create the dist files and test production.

**Comment by ilanbiala** [comment]
If anyone wants to create a PR, I'll quickly merge that in.

**Comment by venetianthief** [comment]
@ilanbiala PR -> https://github.com/meanjs/generator-meanjs/pull/83
