### ISSUE TITLE
0.4.0  $ yo meanjs:crud-module <module-name>  RUNS  $ yo meanjs

### ISSUE THREAD

**Issue by metasean** [meanjs/generator-meanjs#79]
I've got a new 0.4.0 MEAN.js app.  

When I try to generate a new crud-module named "meets" by running:  

    yo meanjs:crud-module meets

I am greeted by:
```
CompName:AppName metasean$ yo meanjs:crud-module meets

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

You're using the official MEAN.JS 0.4 generator.
? What would you like to call your application? (MEAN) 
```

Moved from https://github.com/meanjs/mean/issues/437

**Comment by metasean** [comment]
For anybody else wanting to run the equivalent of `yo meanjs:crud-module <module_name>` in the 0.4.0 generator, then new command is:

    yo meanjs:vertical-module meets

@amoshaviv, @keshavos, and other official team members, are there plans to merge the functionality back in (i.e. to make `yo meanjs:crud-module <module_name>` work) or should user documentation be updated to reference the vertical-module command instead of the crud-module command?

**Comment by TsarS** [comment]
Same issue with     yo meanjs:vertical-module meets

"What would you like to call your application?"

**Comment by Shrizzy** [comment]
@TsarS I had a similar issue when I first installed the 0.4.0 generator, turned out that I had the generator-meanjs installed twice on my machine in different locations, and it was mapping to the old version (both generators are installed using the same folder name). 
I've been using the vertical module generator for a few months now with no issues.
Perhaps check if you have a similar issue, or perhaps an issue with your PATHs?

**Comment by adskdave** [comment]
I'm having this exact issue at the moment.
@Shrizzy how can I see which yo meanjs: is running?

I'm happy to delete / re-install some packages if needed.

Thanks.

**Comment by MikeWatsonDev** [comment]
how can i check if have generator-meanjs installed twice ?
npm -g ls --depth=0
/usr/local/lib
├── bower@1.5.2
├── generator-meanjs@0.4.1
├── grunt-cli@0.1.13
├── npm@2.11.2
└── yo@1.4.8

I have the same problem, but here I only see one version of generator, I tried both 
yo meanjs:vertical-module listings && yo meanjs:crud-module listings, still launching the app generator

**Comment by yusiswtor** [comment]
Same issue for me - is it an issue with 0.4.1 maybe?

**Comment by ilanbiala** [comment]
We have no subgenerators for 0.4.1 as of now. We will have them out soon.

**Comment by firasm101** [comment]
Hello,

I'm having the same issue, tried all that is suggested above - still doesn't work.
What I did as a temporary workaround is to downgrade the "generator-meanjs" npm package to lower than "0.4.1".
The one before "0.4.1" that is available for installation is "0.1.12" so I hope I won't encounter any issues going forward with that as it seems like an old version.

Remove the current version:
```
sudo npm remove -g generator-meanjs
```

View available versions for installation:
```
npm view generator-meanjs versions
```

Install the most recent version after "0.4.1":
```
sudo npm install -g generator-meanjs@(VERSION NUMBER)
```
Hope this helps.

Thank You,
Firas

**Comment by ilanbiala** [comment]
@firasm101 we are no longer supporting that code and that version of the generator, so I do not recommend it.

**Comment by hanssl** [comment]
Do you have a timeline for when the generators will be available for 0.4.1?

**Comment by ilanbiala** [comment]
@hanssl no, there is a PR open #131, but anything you contribute will help speed up the process.

**Comment by aquadestructor** [comment]
Is there any alternative for generating modules before the generator officially launches?

**Comment by Dwiea** [comment]
Still an issue?

**Comment by sugeun** [comment]
@Dwiea I'm having the same issue. It worked correctly by downgrading generator-meanjs version as @firasm101 suggested. I don't particularly like this workaround cause I wanted to use the chat example as a start of my project.

**Comment by GeorgeWilliamson** [comment]
Hi I'm one of the many I would say stuck at day 9 on the 30 day challenge. (re crud generator) I see from above the 0.4.0 works for a vertical-module. How can I download this generator ? Have tried sudo npm install --global meanjs/generator-meanjs0.4.0  , does not work. Is there any chance of having a stable version of meanjs, I'm using Ubuntu 14  and it's really a hit or miss exercise building meanjs with 0.4.1 version, Centos 7 seems to build a lot better, but prefer to stay with Ubuntu.

Cheers,

George

**Comment by GPnow** [comment]
@GeorgeWilliamson  any progress mate ???

**Comment by bhavik3184** [comment]
yo meanjs:vertical-module doesn't work on my windows 8.1 machine.

**Comment by samhendrickx** [comment]
Same issue here

**Comment by GPnow** [comment]
they already said they are working on the crud sub-generator for 0.4x,so do it manually for now i guess :+1:

**Comment by front-thinking** [comment]
Same issue here
+1

**Comment by dbelieves** [comment]
4 days ago it has been updated...

but still i am facing the issue...

**Comment by nithinreddygaddam** [comment]
how do u do it manually?

**Comment by GPnow** [comment]
Simple,copy paste the Article crud module,and rename everything inside. :+1:

**Comment by dbelieves** [comment]
@GPnow , that takes way too much time :|

**Comment by calarconpieriz** [comment]
So the conclusion is that there is no CRUD generator anymore?

**Comment by ilanbiala** [comment]
@calarconpieriz we are still finalizing thatPR,  so hopefully very soon.

**Comment by shubhank-srivastava** [comment]
@GPnow and @dbelieves  Try this https://github.com/shubhank-srivastava/meanjs-module-generator
A small script that I wrote that won't take much time by just doing `node modgen articles products` to create a products module similar to articles module.

**Comment by GeorgeWilliamson** [comment]
Thank you,

Shubhank Srivastava




On Thu, Dec 31, 2015 at 9:50 AM, Shubhank Srivastava <
notifications@github.com> wrote:

> @GPnow <https://github.com/GPnow> and @dbelieves
> <https://github.com/dbelieves> Try this
> https://github.com/shubhank-srivastava/meanjs-module-generator
> A small script that I wrote that won't take much time by just doing node
> modgen articles products to create a products module similar to articles
> module.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/generator-meanjs/issues/79#issuecomment-168096817>
> .
>



-- 
Best Regards.

George Williamson.


Mobile     +61439749014

**Comment by mrjohnskelton** [comment]
See https://github.com/node-inspector/v8-debug/issues/7 for a suggested fix by @surprisetalk - worked for me on a shiny new version set

**Comment by reuf** [comment]
@shubhank-srivastava  - thanks for the script - saves the day.

**Comment by Aabir1** [comment]
i am not able to use this=> sudo yo meanjs:crud-module costomers. please help me . i am stuck from yesturday

**Comment by ilanbiala** [comment]
@Aabir1 what do you see when you run that? Have you installed 0.4.3?

**Comment by mdata2** [comment]
@ilanbiala.. Are there any updates on the fix for ver 0.4.3?

**Comment by fennrussel** [comment]
Same problem
C:\test> yo meanjs:crud-module meets
Error meanjs:crud-module meets

You don't seem to have a generator with the name meanjs:crud-module installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 16 registered generators run yo with the `--help` option.

Please help me

**Comment by ilanbiala** [comment]
The command is `mean-module`. Sorry for the confusion guys.

**Comment by Siddharth-ss42279** [comment]
facing same problem as of @fennrussel  ,  any solution ???

**Comment by mahmoudalcharif** [comment]
@ilanbiala The mean-module  command has created any empty directory and not CRUD ready structure

**Comment by mahmoudalcharif** [comment]
Thank you @shubhank-srivastava. Your script did the job :+1:

**Comment by Siddharth-ss42279** [comment]
@GPnow  can u explain how to make crud module manualy??

**Comment by Matt-Webb** [comment]
Why is this issue marked as closed? I can't find a solution anywhere in here. 

I am running MEAN version `0.4.2` with generator-meanjs version `0.4.3` neither of the following commands work:

`yo meanjs:vertical-module {NAME}`

or

`yo meanjs:crud-module {NAME}`

I get the following message:

```
You don't seem to have a generator with the name meanjs:vertical-module installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
```

The registered generators I have are:

```
Available Generators:

  meanjs
    angular-config
    angular-controller
    angular-directive
    angular-filter
    angular-route
    angular-service
    angular-tests
    angular-view
    express-controller
    express-model
    express-route
    express-tests
    mean-module
```

Does't anyone know how to resolve this?

**Comment by ilanbiala** [comment]
Use `mean-module`.

**Comment by Matt-Webb** [comment]
@ilanbiala I tried this, I only get a set of empty directories?!

**Comment by Siddharth-ss42279** [comment]
yes, mean-module creates only empty directories.Rather you can use Article crud module @Matt-Webb

**Comment by Matt-Webb** [comment]
Can you initiate the Article Crude module after the initial project create? @Siddharth-ss42279 

I guess I could create an empty project with the Article Crude and copy is across?!

**Comment by Siddharth-ss42279** [comment]
yes, you can create project with Article module, than copy that article module it to your main project .it works fine...! @Matt-Webb

**Comment by Matt-Webb** [comment]
Okay I just tried to do this, renaming the files and references from "articles" to my new module name, this is a **massively time consuming task**, even with a project Find + Replace, the individual files need renaming too!

Surely there is a fix for this generator???

**Comment by amercode** [comment]
I came up with a hack to fix this issue: please check out my video:
https://www.youtube.com/watch?v=Nkpdp1ofux8

**Comment by ilanbiala** [comment]
Just published 0.4.4, see if that fixes your issues.

**Comment by junit38** [comment]
@Matt-Webb 
This may help you:

```
var=$1
if [ -n "$var" ]; then
	CRUDNAME=$1
	CRUDNAMEUPPERCASE=`echo ${CRUDNAME:0:1} | tr  '[a-z]' '[A-Z]'`${CRUDNAME:1}
	FOLDERNAME=$CRUDNAME's'
	cp -R modules/articles modules/$CRUDNAME's'
	find modules/$FOLDERNAME -type f -print0 | xargs -0 sed -i -e 's/Article/'$CRUDNAMEUPPERCASE'/g'
	find modules/$FOLDERNAME -type f -print0 | xargs -0 sed -i -e 's/article/'$CRUDNAME'/g'
	rm modules/$FOLDERNAME/**/*-e
	rm modules/$FOLDERNAME/**/**/*-e
	for file in modules/$FOLDERNAME/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
	for file in modules/$FOLDERNAME/**/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
else
    echo "Usage: sh file.sh [crud-name]"
fi
```

**Comment by atomixnmc** [comment]
I hope this has a solution now?

I have 0.4.4 and it still not working, asking for the root project which is pretty nonsense:

yo meanjs:mean-module game
**undefined         **                                                            
You're using the official MEAN.JS generator.                                  
? What mean.js version would you like to generate? (Use arrow keys)           
  master                                                                      
> 0.4.0                                                                       
  0.4.1
? In which folder would you like the project to be generated? This can be changed later. (mean)

Is this issue really fixed?

**Comment by ilanbiala** [comment]
@UndeadBaneGitHub can you provide some info and maybe even create PRs for some docs of the new subgenerators?

**Comment by UndeadBaneGitHub** [comment]
@ilanbiala Sure!

**Comment by benobab** [comment]
@junit38 this version works properly (the actual version of meanjs contains also some /admin folders etc) -> that means we have to go 1 level deeper for the rm and the rename of files ;-) 

Thanks for your original script, it saves me a lot of time every day!

```sh
var=$1
if [ -n "$var" ]; then
    CRUDNAME=$1
    CRUDNAMEUPPERCASE=`echo ${CRUDNAME:0:1} | tr  '[a-z]' '[A-Z]'`${CRUDNAME:1}
    FOLDERNAME=$CRUDNAME's'
    # Create new folder
    cp -R modules/articles modules/$FOLDERNAME
    # Do the find/replace in all the files
    find modules/$FOLDERNAME -type f -print0 | xargs -0 sed -i -e 's/Article/'$CRUDNAMEUPPERCASE'/g'
    find modules/$FOLDERNAME -type f -print0 | xargs -0 sed -i -e 's/article/'$CRUDNAME'/g'
    # Delete useless files due to sed
    rm modules/$FOLDERNAME/**/*-e
    rm modules/$FOLDERNAME/**/**/*-e
    rm modules/$FOLDERNAME/**/**/**/*-e
    # Rename all the files
    for file in modules/$FOLDERNAME/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
    for file in modules/$FOLDERNAME/**/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
    for file in modules/$FOLDERNAME/**/**/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
else
    echo "Usage: sh rename-module.sh [crud-name]"
fi
```

**Comment by junit38** [comment]
@benobab You'r welcome !

Thanks for the improvement.

**Comment by sanjeet05** [comment]
Easy way to do this in ubuntu:
Please follow the instructions....

# copy article module and rename as **customers**
# open terminal inside your project(meanjs)
# modify these two variables as like below
# copy all the code and paste it to the terminal
	
CRUDNAME="customer"
CRUDNAMEUPPERCASE="Customer"
FOLDERNAME=$CRUDNAME's'

# Do the find/replace in all the files
find modules/$FOLDERNAME -type f -print0 | xargs -0 sed -i -e 's/Article/'$CRUDNAMEUPPERCASE'/g'
find modules/$FOLDERNAME -type f -print0 | xargs -0 sed -i -e 's/article/'$CRUDNAME'/g'

# Rename all the files
for file in modules/$FOLDERNAME/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
for file in modules/$FOLDERNAME/**/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
for file in modules/$FOLDERNAME/**/**/**/*article* ; do mv $file ${file//article/$CRUDNAME} ; done
