### ISSUE TITLE
Error with yo meanjs error access morgan 

### ISSUE THREAD

**Issue by radjivC** [meanjs/generator-meanjs#81]
Hi, when I use the yo generator with sudo or without sudo, the generator can't read the .npm/ folder  

![74f9a9d2-bdad-11e4-9d4c-9583c620a922](https://cloud.githubusercontent.com/assets/5714138/6572689/776e7128-c714-11e4-8390-1c900281f3fc.png)

I made a github gist with my npm log at this adress, if you need more information.  https://gist.github.com/radjivC/44661c70ee8e3edac98c.

I opened an issues on https://github.com/meanjs/mean/issues/430 , but @ilanbiala advices me to put the issues because it's a generator problem.

Thank you

**Comment by AlexisTM** [comment]
Hello, you should correct the rights of your ~/.npm folder...

sudo chown -R username:group ~/.npm

**Comment by radjivC** [comment]
It's working for me, thanks
