### ISSUE TITLE
Incorrect glob pattern on file config/assets/default.js

### ISSUE THREAD

**Issue by outreal** [meanjs/generator-meanjs#86]
Hi,
There's a problem with the glob pattern on the file config/assets/default.js, on server.routes (line 45). Actually, it's:
```
routes: ['modules/*[!core]/server/routes/**/*.js', 'modules/core/server/routes/**/*.js'],
```
And it should be:
```
routes: ['modules/!(core)/server/routes/**/*.js', 'modules/core/server/routes/**/*.js'],
```
Otherwise it excludes all module names which end with `c`, `o`, `r` or `e`.

And thanks for this great generator :)

**Comment by ilanbiala** [comment]
@outreal can you create a PR?

**Comment by outreal** [comment]
@ilanbiala yes, I think I can. I've never done it before, though.
I'm a developer but I always used SVN for source control. Could you please explain me why is it simpler for you if I fork your projet, commit my small change and create a PR instead of just making this change yourself?

Please, don't take me wrong, I have no problems with doing it, I'm just trying to understand what the benefits of doing PRs are :-)

**Comment by ilanbiala** [comment]
It's to give people who aren't as experienced with OSS a chance to become more familiar and allow OSS developers to spend more time working on fixing bigger bugs and implementing new features instead of having to spend a lot of time working on 1-2 line fixes.
