### ISSUE TITLE
Error: yo meanjs

### ISSUE THREAD

**Issue by sapna1402** [meanjs/generator-meanjs#97]
_-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

You're using the official MEAN.JS generator.
? What would you like to call your application? firstapp
? How would you describe your application? (Full-Stack JavaScript with MongoDB, ? How would you describe your application? Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? (MongoDB? How would you describe your application in comma seperated key words? MongoDB, Express, AngularJS, Node.js
? What is your company/author name? sapna
? Would you like to generate the article example CRUD module? No
? Which AngularJS modules would you like to include? ngCookies, ngAnimate, ngTouch, ngSanitize
   create app/views/404.server.view.html
   create app/views/500.server.view.html
   create app/views/index.server.view.html
   create app/views/layout.server.view.html
   create app/views/templates/reset-password-confirm-email.server.view.html
   create app/views/templates/reset-password-email.server.view.html
   create app/controllers/core.server.controller.js
   create app/controllers/users.server.controller.js
   create app/controllers/errors.server.controller.js
   create app/controllers/users/users.authentication.server.controller.js
   create app/controllers/users/users.authorization.server.controller.js
   create app/controllers/users/users.password.server.controller.js
   create app/controllers/users/users.profile.server.controller.js
   create app/models/user.server.model.js
   create app/routes/core.server.routes.js
   create app/routes/users.server.routes.js
   create app/tests/user.server.model.test.js
   create public/application.js
   create public/humans.txt
   create public/robots.txt
   create public/modules/users/config/users.client.config.js
   create public/modules/users/config/users.client.routes.js
   create public/modules/users/controllers/authentication.client.controller.js
   create public/modules/users/controllers/password.client.controller.js
   create public/modules/users/controllers/settings.client.controller.js
   create public/modules/users/css/users.css
   create public/modules/users/img/buttons/facebook.png
   create public/modules/users/img/buttons/github.png
   create public/modules/users/img/buttons/google.png
   create public/modules/users/img/buttons/linkedin.png
   create public/modules/users/img/buttons/twitter.png
   create public/modules/users/services/authentication.client.service.js
   create public/modules/users/services/users.client.service.js
   create public/modules/users/tests/authentication.client.controller.test.js
   create public/modules/users/users.client.module.js
   create public/modules/users/views/authentication/signin.client.view.html
   create public/modules/users/views/authentication/signup.client.view.html
   create public/modules/users/views/password/forgot-password.client.view.html
   create public/modules/users/views/password/reset-password-invalid.client.view.html
   create public/modules/users/views/password/reset-password-success.client.view.html
   create public/modules/users/views/password/reset-password.client.view.html
   create public/modules/users/views/settings/change-password.client.view.html
   create public/modules/users/views/settings/edit-profile.client.view.html
   create public/modules/users/views/settings/social-accounts.client.view.html
   create public/modules/core/config/core.client.routes.js
   create public/modules/core/controllers/header.client.controller.js
   create public/modules/core/controllers/home.client.controller.js
   create public/modules/core/css/core.css
   create public/modules/core/img/brand/favicon.ico
   create public/modules/core/img/brand/logo.png
   create public/modules/core/img/loaders/loader.gif
   create public/modules/core/services/menus.client.service.js
   create public/modules/core/tests/header.client.controller.test.js
   create public/modules/core/tests/home.client.controller.test.js
   create public/modules/core/views/home.client.view.html
   create public/modules/core/core.client.module.js
   create config/strategies/facebook.js
   create config/strategies/github.js
   create config/strategies/google.js
   create config/strategies/linkedin.js
   create config/strategies/local.js
   create config/strategies/twitter.js
   create config/config.js
   create config/init.js
   create config/express.js
   create config/passport.js
   create karma.conf.js
   create gruntfile.js
   create server.js
   create Procfile
   create fig.yml
   create Dockerfile
   create generate-ssl-certs.sh
   create README.md
   create LICENSE.md
   create .bowerrc
   create .csslintrc
   create .editorconfig
   create .jshintrc
   create .gitignore
   create .slugignore
   create .travis.yml
   create config/env/all.js
   create config/env/development.js
   create config/env/production.js
   create config/env/test.js
   create config/env/secure.js
   create public/config.js
   create public/modules/core/views/header.client.view.html
   create package.json
   create bower.json
npm WARN package.json firstapp@0.0.1 No repository field.
npm WARN package.json firstapp@0.0.1 No license field.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-ng-annotate will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-contrib-cssmin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-csslint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.2 included from grunt-node-inspector will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-nodemon will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-jshint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency mocha@>=1.20.0 included from grunt-mocha-test will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-uglify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@0.4.x included from grunt-karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-watch will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN excluding symbolic link build/defs-config.json -> ../defs-config.json
npm WARN optional dep failed, continuing fsevents@0.3.6
 
> phantomjs@1.9.17 install /home/sapna/Project/firstMeanApp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Extracting tar contents (via spawned process)
Removing /home/sapna/Project/firstMeanApp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1436604951351/phantomjs-1.9.8-linux-x86_64 -> /home/sapna/Project/firstMeanApp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/sapna/Project/firstMeanApp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
 
> kerberos@0.0.11 install /home/sapna/Project/firstMeanApp/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/sapna/Project/firstMeanApp/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `/home/sapna/Project/firstMeanApp/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos/build'
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
 
> bson@0.2.21 install /home/sapna/Project/firstMeanApp/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/sapna/Project/firstMeanApp/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory `/home/sapna/Project/firstMeanApp/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson/build'
 
> kerberos@0.0.11 install /home/sapna/Project/firstMeanApp/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/sapna/Project/firstMeanApp/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
make: Leaving directory `/home/sapna/Project/firstMeanApp/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
 
> bson@0.2.21 install /home/sapna/Project/firstMeanApp/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/sapna/Project/firstMeanApp/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory `/home/sapna/Project/firstMeanApp/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
 
> v8-profiler@5.2.9 preinstall /home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
>  

 
> v8-debug@0.4.6 preinstall /home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
>  

 
> ws@0.4.32 install /home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/build'
npm WARN optional dep failed, continuing default-browser-id@1.0.2

> ws@0.4.32 install /home/sapna/Project/firstMeanApp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/sapna/Project/firstMeanApp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/home/sapna/Project/firstMeanApp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.6","npm":"2.13.0"})
-
> v8-profiler@5.2.9 install /home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.9/node-v14-linux-x64/profiler.node" is installed via remote

> v8-debug@0.4.6 install /home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/home/sapna/Project/firstMeanApp/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v14-linux-x64/debug.node" is installed via remote

> firstapp@0.0.1 postinstall /home/sapna/Project/firstMeanApp
> bower install --config.interactive=false

bower EACCES        EACCES, open '/home/sapna/.cache/bower/registry/bower.herokuapp.com/lookup/angular-mocks_f6200'

Stack trace:
Error: EACCES, open '/home/sapna/.cache/bower/registry/bower.herokuapp.com/lookup/angular-mocks_f6200'
    at Error (native)

Console trace:
Trace
    at StandardRenderer.error (/home/sapna/Project/firstMeanApp/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/home/sapna/Project/firstMeanApp/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/home/sapna/Project/firstMeanApp/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/sapna/Project/firstMeanApp/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/home/sapna/Project/firstMeanApp/node_modules/bower/node_modules/q/q.js:797:24)
    at /home/sapna/Project/firstMeanApp/node_modules/bower/node_modules/q/q.js:823:30
    at Promise.when (/home/sapna/Project/firstMeanApp/node_modules/bower/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/home/sapna/Project/firstMeanApp/node_modules/bower/node_modules/q/q.js:741:41)
    at /home/sapna/Project/firstMeanApp/node_modules/bower/node_modules/q/q.js:557:44

System info:
Bower version: 1.3.12
Node version: 0.12.6
OS: Linux 3.16.0-30-generic x64

npm ERR! Linux 3.16.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.6
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE
npm ERR! firstapp@0.0.1 postinstall: `bower install --config.interactive=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the firstapp@0.0.1 postinstall script 'bower install --config.interactive=false'.
npm ERR! This is most likely a problem with the firstapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false
npm ERR! You can get their info via:
npm ERR!     npm owner ls firstapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sapna/Project/firstMeanApp/npm-debug.log

**Comment by manasj1947** [comment]
any solution on this?
