### ISSUE TITLE
Two users can associate the same providerProfile to their accounts

### ISSUE THREAD

**Issue by kristianbenoit** [meanjs/generator-meanjs#99]
Two users can associate the same providerProfile to their accounts and a user might do it unexpectedly.

Step to repeat:
1. Create a user with a local provider, associate a facebook account.
2. Create a user with a google provider, associate the same facebook account to it.

The facebook account is not removed from the first user and is added to the second. Which user should signin when the he signin from a Facebook provider ?

**Comment by lirantal** [comment]
can you check if this is resolved in 0.4.0?

**Comment by kristianbenoit** [comment]
It does not seems resolved. I did not test, but `User.saveOAuthUserProfile` seems to be the same code as the current released version and does not check if the email is already in the database before creating a user or if the provider is already in the database before adding the provider to the user. (https://github.com/meanjs/generator-meanjs/blob/0.4-dev/app/templates/modules/users/server/controllers/users/users.authentication.server.controller.js#L104)

**Comment by lirantal** [comment]
got it.
would be great if you can provide a PR for 0.4.0 that fixes this.
